# Generated by Django 5.0.12 on 2025-09-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationrecommendation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
