# Generated by Django 5.0.12 on 2025-06-08 17:26

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(help_text='Explain why you would like to attend PyCon Africa and how it would benefit you.')),
                ('contribution', models.TextField(help_text='Describe any contributions you have made to Python, PyCon Africa, or the broader tech community.')),
                ('financial_need', models.TextField(help_text='Please explain your financial circumstances and why you need this grant.')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say'), ('other', 'Other')], default='prefer_not_to_say', help_text='Gender identity', max_length=20)),
                ('gender_details', models.TextField(blank=True, default='', help_text="Please provide more details if you selected 'Other'")),
                ('current_role', models.CharField(choices=[('high_school_student', 'High School Student'), ('undergraduate_student', 'Undergraduate Student'), ('graduate_student', 'Graduate Student'), ('employed', 'Employed'), ('self_employed', 'Self-employed/Freelancer'), ('between_jobs', 'Between jobs/Seeking opportunities'), ('retired', 'Retired'), ('prefer_not_to_say', 'Prefer not to say'), ('other', 'Other')], default='prefer_not_to_say', help_text='Which of the following best describes your current role?', max_length=30)),
                ('current_role_details', models.TextField(blank=True, default='', help_text="Please provide more details if you selected 'Other'")),
                ('transportation_type', models.CharField(blank=True, choices=[('air_travel', 'Air travel'), ('ground_travel', 'Ground travel (bus, car, train)')], default='', help_text='What type of transportation were you planning to take?', max_length=20)),
                ('travel_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated travel costs in USD', max_digits=10, null=True)),
                ('travel_from_city', models.CharField(blank=True, default='', help_text='City you will be travelling from', max_length=100)),
                ('travel_from_country', django_countries.fields.CountryField(blank=True, help_text='Country you will be travelling from', max_length=2, null=True)),
                ('request_accommodation', models.BooleanField(default=False, help_text='Do you need assistance with accommodation?')),
                ('accommodation_nights', models.PositiveIntegerField(blank=True, help_text='Number of nights you need accommodation for', null=True)),
                ('request_ticket', models.BooleanField(default=False, help_text='Do you need a conference ticket?')),
                ('additional_info', models.TextField(blank=True, default='', help_text='Is there anything else not covered above you would like to tell us?')),
                ('request_travel', models.BooleanField(default=False, help_text='Do you need assistance with travel costs?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grant_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
