# Generated by Django 5.0.12 on 2026-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='transportation_type',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='travel_amount',
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='contribution',
            field=models.TextField(help_text='Describe any contributions you have made to Python, PyConZA, or the broader tech community.'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='motivation',
            field=models.TextField(help_text='Explain why you would like to attend PyConZA and how it would benefit you.'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='request_accommodation',
            field=models.BooleanField(default=False, help_text='Do you need a hostel bed? We book and pay for it.'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='request_ticket',
            field=models.BooleanField(default=False, help_text='Do you need a free conference ticket?'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='request_travel',
            field=models.BooleanField(default=False, help_text='Do you need a return bus ticket to Cape Town? We book it for you.'),
        ),
    ]
